version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - 5432
  
  backend:
    build: ./server
    ports:
      - 3000:3000
    depends_on:
      - postgres

  frontend:
    build: ./client
    ports:
      - 5000:5000
    depends_on:
      - backend
